<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/carrinho.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>
<style>
  
  .cart-info {border-top:4px solid #0DC3B6}
  .btn-delete,.btn-update { cursor: pointer; }

</style>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

<?php

 function objectToArray($d) {
      if (is_object($d)) {
        // Gets the properties of the given object
        // with get_object_vars function
        $d = get_object_vars($d);
      }
   
      if (is_array($d)) {
        /*
        * Return array converted to object
        * Using __FUNCTION__ (Magic constant)
        * for recursive call
        */
        return array_map(__FUNCTION__, $d);
      }
      else {
        // Return array
        return $d;
      }
    }

if (sizeof ($this->carrinho) > 0) { ?>

<div class="cart-info">
  <table class="table table-striped table-hover">
    <tr>
      <th colspan="2" class="image">Produto</th>
      <th class="quantity">Estoque</th>
      <th class="quantity">Qtde</th>
      <th class="total">Ações</th>
      <th class="price">Valor</th>
      <th class="total">SubTotal</th>
    </tr>
    
   <?php 
    $total = 0;
    $pesoTotal = 0;
    $n = count ($this->carrinho);
    for($i = 0;$i < $n ; $i++){ ?>
      <tr id="<?php echo $this->carrinho[$i]['cod_produto']; ?>">
        
        <td class="image">
          <a href="<?php echo $this->baseUrl() ?>/produto/view/<?php echo $this->RemoveAcentos($this->carrinho[$i]['produto']).'-'.base64_encode($this->carrinho[$i]['cod_produto']); ?>">
            
            <?php 
              if (!empty($this->Data->imagem)) {
                $image = $this->carrinho[$i]['cod_produto'].'/'.$this->carrinho[$i]['imagem'];
              } else {
                $image = '1.jpg';
              }?>
        
            <img src="<?php echo $this->baseUrl() ?>/default/uploads/produtos/<?php echo $image; ?>" class="img-responsive" title="<?php echo $this->carrinho[$i]['produto']; ?>" alt="<?php echo $this->carrinho[$i]['produto']; ?>" height="50" width="50"  />
          </a>
        </td>
        
        <td  class="name">
          <a href="<?php echo $this->baseUrl() ?>/produto/view/<?php echo $this->RemoveAcentos($this->carrinho[$i]['produto']).'-'.base64_encode($this->carrinho[$i]['cod_produto']); ?>">
            <?php echo $this->carrinho[$i]['produto']; ?>
          </a>
        </td>
        
        <td class="quantity">
          <input type="text" size="3" maxlength="3" readonly="true" value="<?php echo $this->carrinho[$i]['quantidade']; ?>" id="estoque-<?php echo $this->carrinho[$i]['cod_produto']; ?>" name="estoque" />
        </td>

        <td class="quantity">
          <input type="text" size="3" maxlength="3" value="<?php echo $this->carrinho[$i]['qtde']; ?>" id="qtde-<?php echo $this->carrinho[$i]['cod_produto']; ?>" name="qtde" />
        </td>
        
        <td class="total">
          <a class="btn-update" style="margin-right:10px;" rel="<?php echo $this->carrinho[$i]['cod_produto']; ?>">
            <i class="fa fa-refresh fa-lg"></i>
          </a> 

          <a class="btn-delete" rel="<?php echo $this->carrinho[$i]['cod_produto']; ?>">
            <i class="fa fa-trash-o fa-lg" data-original-title="Remove"> </i>
          </a>
        </td>
        
         <td class="price">
          
          <?php 

            $sessionCustomer = new Zend_Session_Namespace('sessionCustomer');
            
            if ($sessionCustomer->id) {

              switch ($sessionCustomer->grupo) {
                case 1:
                $valor = 'preco_varejo';
                break;

                case 2:
                $valor = 'preco_atacado';
                break;

                case 3:
                $valor = 'preco_distribuidor';
                break; 

              }  

            } else {
            
              $valor = 'preco_varejo';

            }    

            echo $this->Valor($this->carrinho[$i][$valor]); 

          ?>

        </td>
        <td class="total">
          <?php 
            
            $sub = $this->Valor($this->carrinho[$i][$valor]*$this->carrinho[$i]['qtde']); 

            $total = $total + $this->carrinho[$i][$valor]*$this->carrinho[$i]['qtde'];

            $pesoTotal = $pesoTotal + $this->carrinho[$i]['peso']*$this->carrinho[$i]['qtde'];

            echo $sub;
          ?>
          </td>
      </tr>
    <?php } ?>

      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="price"><b>Total</b></td>
        <td class="total"><b><?php echo $this->Valor($total); ?></b></td>
      </tr>
    
  </table>
</div>

<?php

  $Model            = new Model_Cliente();
  $sessionCustomer  = new Zend_Session_Namespace('sessionCustomer');

  $r = $Model->getClientById($sessionCustomer->id);

  $cep = str_replace('-', '', $r->cep);

  $service = array( '40010','41106' );
  $zipOrigin = '38022220';
  $zipDestination = $cep;
  $height = 20;
  $width = 20;
  $diameter = 0;
  $length = 30;
  $weight = $pesoTotal;

  $correios = new Momesso_Plugins_Frete($service, $zipOrigin, $zipDestination, $height, $width, $diameter, $length, $weight);

  $res = objectToArray($correios->calculateShipping());
  
  $sessionCustomer->frete       = str_replace(',', '.',$res[40010]['Valor']);
  $sessionCustomer->tipoFrete   = 'SEDEX';

?>

  <table class="table table-striped table-hover">
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><input type="radio" name="frete" id="Sedex" class="frete" value="<?php echo $res[40010]['Valor']; ?>" checked> SEDEX</td>
      <td><?php echo $res[40010]['PrazoEntrega'] + 2; ?> dias úteis</td>
      <td><?php echo 'R$ '.$res[40010]['Valor']; ?></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><input type="radio" name="frete" id="Pac" class="frete" value="<?php echo $res[41106]['Valor']; ?>"> PAC</td>
      <td><?php echo $res[41106]['PrazoEntrega'] + 2; ?> dias úteis</td>
      <td><?php echo 'R$ '.$res[41106]['Valor']; ?></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><input type="radio" name="frete" id="Transportadora" class="frete" value="0.00"> Transportadora com Frete à Cobrar</td>
      <td></td>
      <td>Á Cobrar</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><input type="hidden" id="compra" value="<?php echo $total; ?>" /></td>
      <td class="price"><b>Total da Compra</b></td>
      <td class="total" id="totalCompra"><b><?php echo $this->Valor($total+str_replace(',', '.',$res[40010]['Valor'])); ?></b></td>
    </tr>
  </table>



  <div class="container">
    
    <a href="<?php echo $this->baseUrl() ?>/" class="btn btn-primary pull-left">Continuar Comprando</a>
    
    <a href="<?php echo $this->baseUrl() ?>/carrinho/finaliza" class="btn btn-primary pull-right">Fazer o Pagamento</a>

  </div>

<?php } else { ?>
  
  <div class="alert alert-info">Seu carrinho esta vazio.</div><br />
  <a href="<?php echo $this->baseUrl() ?>/produto/category/tintas-para-tatuagem/Mg==" class="btn btn-primary pull-left">Comprar</a>

<?php } ?>

</div>

<br clear="all" />
