<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/carrinho.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>
<style>
  
  .cart-info {border-top:4px solid #0DC3B6}
  .btn-delete,.btn-update { cursor: pointer; }

</style>
<?php $sessionCustomer = new Zend_Session_Namespace('sessionCustomer'); ?>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="cart-info">
  <table class="table table-striped table-hover">
    <tr>
      <th colspan="2" class="image">Produto</th>
      <th class="quantity">Qtde</th>
      <th class="price">Valor</th>
      <th class="total">Subtotal</th>
    </tr>
    
    <?php 
    $total = 0;
    $n = count ($this->carrinho);
    for($i = 0;$i < $n ; $i++){ ?>
      <tr id="<?php echo $this->carrinho[$i]['cod_produto']; ?>">
        
        <td class="image">
          <a href="<?php echo $this->baseUrl() ?>/produto/view/<?php echo $this->RemoveAcentos($this->carrinho[$i]['produto']).'-'.base64_encode($this->carrinho[$i]['cod_produto']); ?>">
            
            <?php 
              if (!empty($this->Data->imagem)) {
                $image = $this->carrinho[$i]['cod_produto'].'/'.$this->carrinho[$i]['imagem'];
              } else {
                $image = '1.jpg';
              }?>
        
            <img src="<?php echo $this->baseUrl() ?>/default/uploads/produtos/<?php echo $image; ?>" class="img-responsive" title="<?php echo $this->carrinho[$i]['produto']; ?>" alt="<?php echo $this->carrinho[$i]['produto']; ?>" height="50" width="50"  />
          </a>
        </td>
        
        <td  class="name">
          <a href="<?php echo $this->baseUrl() ?>/produto/view/<?php echo $this->RemoveAcentos($this->carrinho[$i]['produto']).'-'.base64_encode($this->carrinho[$i]['cod_produto']); ?>">
            <?php echo $this->carrinho[$i]['produto']; ?>
          </a>
        </td>
        
        <td class="quantity">
          <?php echo $this->carrinho[$i]['qtde']; ?>
        </td>
        
        <td class="price">
          
          <?php 

            $sessionCustomer = new Zend_Session_Namespace('sessionCustomer');
            
            if ($sessionCustomer->id) {

              switch ($sessionCustomer->grupo) {
                case 1:
                $valor = 'preco_varejo';
                break;

                case 2:
                $valor = 'preco_atacado';
                break;

                case 3:
                $valor = 'preco_distribuidor';
                break; 

              }  

            } else {
            
              $valor = 'preco_varejo';

            }    

            echo $this->Valor($this->carrinho[$i][$valor]); 

          ?>

        </td>
        <td class="total">
          <?php 
            
            $sub = $this->Valor($this->carrinho[$i][$valor]*$this->carrinho[$i]['qtde']); 

            $total = $total + $this->carrinho[$i][$valor]*$this->carrinho[$i]['qtde'];

            echo $sub;
          ?>
          </td>
      </tr>
    <?php } ?>

      <tr>
        <td class="image">&nbsp;</td>
        <td class="name">&nbsp;</td>
        <td class="quantity">&nbsp;</td>
        <td class="price"><b>Total</b></td>
        <td class="total"><b><?php echo $this->Valor($total+$sessionCustomer->frete); ?></b></td>
      </tr>
    
  </table>
</div>


<div class="container">
  
  <a href="<?php echo $this->baseUrl() ?>/" class="btn btn-primary pull-left">Continuar Comprando</a>

  <form id="form-paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <!--Tipo do botão-->
    <input type="hidden" name="cmd" value="_cart" />
    <!--Vendedor e URL de retorno, cancelamento e notificação-->
    <input type="hidden" name="business" value="paypal@electricink.com.br" />
    <input type="hidden" name="return" value="http://electricink.com.br/carrinho/paypalretorno/status/1" />
    <input type="hidden" name="cancel" value="http://electricink.com.br/carrinho/paypalretorno/status/2" />
    
    <!--Internacionalização e localização da página de pagamento-->
    <input type="hidden" name="charset" value="utf-8" />
    <input type="hidden" name="lc" value="BR" />
    <input type="hidden" name="country_code" value="BR" />
    <input type="hidden" name="currency_code" value="BRL" />
    <input type="hidden" name="shipping_1" value="<?php echo $sessionCustomer->frete; ?>">
    <!--Informações sobre o produto e seu valor-->
    <input type="hidden" name="upload" value="1">

    <?php for($i = 0;$i < sizeof ($this->carrinho); $i++){ ?>
    <input type="hidden" name="item_name_<?php echo $i+1; ?>" value="<?php echo $this->carrinho[$i]['produto']; ?>">
    <input type="hidden" name="amount_<?php echo $i+1; ?>" value="<?php echo $this->carrinho[$i][$valor]; ?>">
    <input type="hidden" name="quantity_<?php echo $i+1; ?>" value="<?php echo $this->carrinho[$i]['qtde']; ?>" />
    <?php } ?>

    <!--Botão para submissão do formulário-->
    <button type="button" id="btn-paypal" class="btn btn-success pull-right btn-pagamento"><i class="fa fa-credit-card"></i> Pagar com Paypal</button>
  </form>

  <a href="<?php echo $this->baseUrl() ?>/carrinho/boleto" type="button" id="btn-boleto" class="btn btn-success pull-right btn-pagamento"><i class="fa fa-barcode"></i> Pagar com Boleto</a>

  <a href="<?php echo $this->baseUrl() ?>/carrinho/deposito" type="button" id="btn-deposito" class="btn btn-success pull-right btn-pagamento"><i class="fa fa-money"></i> Pagar com Depósito</a>
  
</div>

</div>

<br clear="all" />

<!-- Overlay Paypal-->
<div id="overlay-paypal">
  <div id="back-paypal">
    <img id="icon-paypal" src="https://www.paypalobjects.com/en_US/i/icon/icon_animated_prog_dkgy_42wx42h.gif">
    <h2>Aguarde alguns segundos.</h2> 
    <p id="texto-paypal">Você está sendo redirecionado para um ambiente seguro do PayPal<br /> para finalizar seu pagamento.
    </p>
    <div id="logo-paypal">
      <img src="https://www.paypal-brasil.com.br/logocenter/util/img/logo_paypal.png"/>
    </div>
  </div>
</div>