<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         
        <?php 

        if ($this->Categoria->cod_categoria == 3) { 
            $img = 'md.jpg';
        
        } elseif ($this->Categoria->cod_categoria == 4) { 
            $img = 'maquinas.jpg'; 

        } elseif ($this->Categoria->cod_categoria == 6) { 
            $img = 'essentialcare.jpg';

        } else {

            $img = 'big-1.jpg';
        }         
        ?>

         baseUrl+"/default/uploads/banners/background/<?php echo $img; ?>"

    ], {
        duration: 10000,
        fade: 750
    });

    $('.bs-example-modal-sm').modal();

}
</script>
<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"> 

    <h3> Categorias</h3>
    <ul class="nav nav-list categories">
        
        <?php foreach ($this->Categoria() as $categoria) { ?>
            <li>
                <?php echo $categoria->nome; ?>
                <?php echo $this->Grupo($categoria->cod_categoria); ?>
                
            </li>
        <?php } ?>    

    </ul>

</div>

<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">

    <div class="featureprojectcontianer mt40" id="productlist">
          
        <h3> Produtos - <?php echo $this->Categoria->nome; ?></h3>

        <div class="featureprojectwrap latestprojectcontianer grid">
        
            <ul>
                  
                <?php foreach ($this->Data as $v) { ?>
                    
                    <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="product-list">
                            <div class="relativediv">
                                
                                <a href="<?php echo $this->baseUrl() ?>/produto/grupo/<?php echo $this->RemoveAcentos($v->nome).'/'.base64_encode($v->cod_grupo); ?>">
                                    <img src="<?php echo $this->baseUrl() ?>/default/uploads/grupos/<?php echo $v->imagem; ?>" class="img-responsive" alt="" />
                                </a>
                            </div>
                            
                            <div class="caption">
                                <h3>
                                    <a href="<?php echo $this->baseUrl() ?>/produto/grupo/<?php echo $this->RemoveAcentos($v->nome).'/'.base64_encode($v->cod_grupo)?>">
                                        <?php echo $v->nome; ?>
                                    </a>
                                </h3>
                            </div>
                        </div>
                    </li>

                <?php } ?>
            </ul>
       </div>
	
    </div>
</div>    

<br clear="all" />	

<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">PROMOÇÃO</h4>
      </div>
      <div class="modal-body">
        Lotes em promoção de tintas (15ml) devido proximidade da data de vencimento:<br> <br>
        <ul>
            <li>5 - Bronze (09/2014)</li>
            <li>20 - Cinza azulado 1 - (09/2014)</li>
            <li>30 - Cinza Azulado 2 - (09/2014)</li>
            <li>9 - Lavanda - (12/2014)</li>
            <li>5 - Marrom Claro - (12/2014)</li>
            <li>50 - Mostarda (12/2014)</li>
            <li>25 - Set Sumi 1 - (10/2014)</li>
            <li>26 - Set Sumi 2 - (10/2014)</li>
            <li>22 - Set Sumi 3 - (10/2014)</li>
            <li>16 - Set Sumi 4 - (10/2014)</li>
            <li>30 - Set Sumi 5 - (10/2014)</li>
            <li>31 - Sumi Claro - (12/2014)</li>
            <li>3 - Sumi Escuro - (10/2014)</li>
            <li>13 - Sumi Médio - (10/2014)</li>
            <li>35 - Verde Mar - (12/2014)</li>
            <li>4 - Verde Musgo - (12/2014)</li>
        </ul>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

 