<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/destaque/new">
    <i class="fa fa-plus-circle fa-lg"></i> Novo Destaque
</a>

<br /><br />

<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Destaques</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Ativo</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $rs->nome; ?></td>
                        <td class="center">
                        	<?php 
                        		if($rs->situacao == 1) echo '<span class="label label-success">Sim</label'; else echo '<span class="label label-warning">Não</label>';
                        	?>
                        </td>
                        <td class="center">
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/destaque/edit/id/<?php echo $rs->cod_destaque ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                            <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Excluir" href="<?= $this->BaseUrl() ?>/admin/destaque/delete/id/<?php echo $rs->cod_destaque; ?>" >
                                <i class="fa fa-trash-o fa-lg"></i>
                            </a>
                        </td> 
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->
