<?php echo $this->doctype() ?>
<html lang="pt-br">
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="pt-BR" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <meta name="author" content="Momesso Web Studio - www.momessoweb.com.br - (34) 3316-8682" />
        <meta name="company" content="Momesso Web Studio - www.momessoweb.com.br - (34) 3316-8682" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <? echo $this->headTitle(); ?>
        
        <!-- basic styles -->

        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/jquery-ui-1.10.3.full.min.css" />

        <!-- page specific plugin styles -->

        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/chosen.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/datepicker.css" />

        <!-- fonts -->

        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/ace-fonts.css" />

        <!-- ace styles -->

        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/ace.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/ace-rtl.min.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/ace-skins.min.css" />
        

        <!--[if lte IE 8]>
          <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/admin/assets/css/ace-ie.min.css" />
        <![endif]-->

        <!-- inline styles related to this page -->

        <!-- ace settings handler -->

        <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/ace-extra.min.js"></script>
        
        <?php
        echo $this->headLink();
        echo $this->headScript();
        echo $this->inlineScript();
        
        echo $this->headScript()->setScript('
			var baseUrl = "' . $this->BaseUrl() . '";
			var module = "' . Zend_Controller_Front::getInstance()->getRequest()->getModuleName() . '";
			var controller = "' . Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '";
			var action = "' . Zend_Controller_Front::getInstance()->getRequest()->getActionName() . '";
		');
       
        ?>       
        
    </head>

    <body>
        
        <?php echo $this->partial('header.phtml'); ?>

        <?php echo $this->partial('nav.phtml'); ?>
        
        <div class="page-content">
            <div class="row">
                <div class="col-xs-12">
                    
                    <?php if($this->message){ ?>
                    
                        <div class="alert alert-<?php echo $this->messageType; ?>">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <p><?php echo $this->message; ?></p>
                        </div>
                    
                    <?php } ?>  

                    <?php echo $this->layout()->content; ?>

                 </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
     
        
        <!-- Modal -->
        <div class="modal fade bs-modal-lg" id="modal-base" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel"></h4>
                    </div>
                    <div class="modal-body">
                        <p></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>		


    </body>
    
    <!-- basic scripts -->

    <!--[if !IE]> -->

        <script type="text/javascript">
            window.jQuery || document.write("<script src='<?php echo $this->baseUrl() ?>/admin/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
        </script>

    <!-- <![endif]-->

    <!--[if IE]>
        <script type="text/javascript">
         window.jQuery || document.write("<script src='<?php echo $this->baseUrl() ?>/admin/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
        </script>
    <![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
        if("ontouchend" in document) document.write("<script src='<?php echo $this->baseUrl() ?>/admin/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
    </script>

    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/jquery-ui-1.10.3.full.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/jquery.ui.touch-punch.min.js"></script>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/typeahead-bs2.min.js"></script>

    <script src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src=
    "//cdn.datatables.net/plug-ins/e9421181788/integration/bootstrap/3/dataTables.bootstrap.js"></script>

    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/date-time/bootstrap-datepicker.min.js"></script>

    <!-- page specific plugin scripts -->

    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/jquery.maskedinput.min.js"></script>

    <!-- ace scripts -->

    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/ace-elements.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/admin/assets/js/ace.min.js"></script>

    <!-- inline scripts related to this page -->

        <script type="text/javascript">
            jQuery(function($) {
                
                var oTable = jQuery('.js-registros').dataTable();

                $( ".btn-tooltip" ).tooltip();

                $('.data').datepicker({
                    autoclose:true,
                    format:'dd/mm/yyyy',
                }).next().on(ace.click_event, function(){
                    $(this).prev().focus();
                });
            

                jQuery('#telefone_celular').focusout(function(){
                    var phone, element;
                    element = jQuery(this);
                    element.unmask();
                    phone = element.val().replace(/\D/g, '');
                    if(phone.length > 10) {
                        element.mask("(99) 99999-999?9");
                    } else {
                        element.mask("(99) 9999-9999?9");
                    }
                }).trigger('focusout');

                jQuery(document).on('click','.info', function(e) {
        
                    e.preventDefault();

                    jQuery.ajax({
                        url: baseUrl+jQuery(this).attr('rel'),
                        dataType: 'html',
                        type: 'get',

                        beforeSend: function() {
                            //addMascara();                   
                        },
                        complete: function() {
                            //removeMascara();        
                        },
                        success: function(data) {               
                            jQuery('.modal-header h4').html('Informações');
                            jQuery('.modal-body p').html(data);
                            jQuery('#modal-base').modal({
                                keyboard: false
                            })
                            
                            $('.data').datepicker({
                                format:'dd/mm/yyyy',
                                viewMode:0,
                                language: 'pt-BR'
                            });
                        },
                        error: function(xhr, er) {
                            alert('Error ' + xhr.status + ' - ' + xhr.statusText);
                        }
                    });      
                });

                jQuery(document).on('click','.retorno', function(e) {
        
                    e.preventDefault();

                   jQuery.ajax({
                        url: baseUrl+jQuery(this).attr('rel'),
                        dataType: 'html',
                        type: 'get',

                        beforeSend: function() {
                            //addMascara();                   
                        },
                        complete: function() {
                            //removeMascara();        
                        },
                        success: function(data) {               
                            
                            alert('Produtos retornados ao estoque com sucesso!');
                            location.href=baseUrl+"/admin/pedido";
                        },
                        error: function(xhr, er) {
                            alert('Error ' + xhr.status + ' - ' + xhr.statusText);
                        }
                    }); 

                }); 

                $('.produto-pedido').on('click',function(e) {
        
                    e.preventDefault();

                    jQuery.ajax({
                        url: baseUrl+'/admin/pedido/produtosave/',
                        data: { 

                            id: $(this).attr('rel'),
                            lote_serie: $('#'+$(this).attr('rel')+'lote_serie').val()    
                        },
                        type: 'post',

                        success: function(data) {               
                            
                        },
                        error: function(xhr, er) {
                            alert('Error ' + xhr.status + ' - ' + xhr.statusText);
                        }
                    });      
                });  

                $(".telefone").mask("(99) 9999-9999");
                $("#cep").mask("99999999");
                
                <?php if ($this->Type == 'f') { ?>
                    $("#documento").mask("999.999.999-99");
                <?php } else if ($this->Type == 'j') { ?>
                    $("#documento").mask("99.999.999/9999-99");
               <?php } ?> 

               $('.js-tab').on('click',function(e) {

                    location.href=baseUrl+'/admin/'+$(this).attr('href');

               }) 

               $('.js-busca').on('click',function(e) {

                    e.preventDefault();
                    
                    if ($('#search').val() == '') {
                        alert('Digite um valor para busca');
                    } else {
                        location.href=baseUrl+'/admin/'+$(this).attr('rel')+$('#search').val();
                    }

               }) 
            })
        </script>
	
</html>
