<div id="enviado" class="tab-pane active">
    <?php echo $this->paginationControl($this->Data, 'Sliding', 'render/pagination.phtml') ?>
    <div class="table-responsive">
       <table class="table table-striped table-bordered table-hover" id="">
        <thead>
            <tr>
                <th>Pedido</th>
                <th>Data/Hora</th>
                <th>Cliente</th>
                <th>Valor</th>
                <th>Envio</th>
                <th>Ações</th>
            </tr>
        </thead>   
        <tbody>
            <?php    
            $Model_Cliente = new Model_Cliente();
            foreach ($this->Data as $rs) { 
                $cliente = $Model_Cliente->getClientById($rs->cliente);
                ?>
                <tr>
                    <td><?php echo $rs->cod_pedido; ?></td>
                    <td><?php echo $this->DataHora($rs->created_at); ?></td>
                    <td><?php echo $cliente->fantasia; ?></td>
                    <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                    <td><?php echo $rs->frete_tipo; ?></td>
                    

                    <td class="center">
                        
                        
                        <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                            <i class="fa fa-print fa-lg"></i>  
                        </a>

                        <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                            <i class="fa fa-file fa-lg"></i>  
                        </a>

                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                            <i class="fa fa-gift fa-lg"></i>  
                        </a>
                        
                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                            <i class="fa fa-pencil-square-o fa-lg"></i>  
                        </a>
                    </td>
                    
                </tr>
                <?php } ?>
            </tbody>
        </table> 
        <?php echo $this->paginationControl($this->Data, 'Sliding', 'render/pagination.phtml') ?>         
    </div>
</div>