<script type="text/javascript">
function large_slider_top() {
    $(".large-slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg",
         baseUrl+"/default/uploads/banners/background/big-5.jpg", 
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>

	<section class="container">

		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
				<div class="content-panel-title">
					<!-- Content panel title for padding and border -->
					<h2><?php echo $this->translate("Produtos"); ?></h2>
				</div>
			</div>
			<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<p>Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc
						fermentum dapibus. Morbi lorem ante, malesuada in mollis nec,
						auctor nec massa. Aenean tempus dui eget felis blandit at
						fringilla urna ultrices. Suspendisse feugiat, ante et viverra
						lacinia, lectus sem lobortis dui, ultricies consectetur leo mauris
						at tortor.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<div class="boxgrid slideright">
						<img class="cover" src="<?php echo $this->baseUrl() ?>/default/uploads/categoria/pigmentos_home_mini220x200.jpg" alt="Máquinas" />
						<h3>Tintas para tatuagens</h3>
						<p>53 cores de tintas para tatuagens<br/><br><a class="soft-hover" href="#">Ver todas as cores</a></p>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<div class="boxgrid slideright">
						<img class="cover" src="<?php echo $this->baseUrl() ?>/default/uploads/categoria/pigmentos_home_mini220x200.jpg" alt="Máquinas" />
						<h3>Pigmentos para MD</h3>
						<p>53 cores de tintas, pigmentos e maquiagem definitiva<br/><br><a class="soft-hover" href="#">Ver todas as cores</a></p>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<div class="boxgrid slideright">
						<img class="cover" src="<?php echo $this->baseUrl() ?>/default/uploads/categoria/maquinas_home_mini220x200.jpg" alt="Pigmentos" />
						<h3>Máquinas</h3>
						<p>
							<br/><br><a class="soft-hover" href="#">Veja também as máquinas rotativas de alumínio</a>
						</p>
					</div>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
				<div class="content-panel-title">
					<!-- Content panel title for padding and border -->
					<h2><?php echo $this->translate("Tatuadores"); ?></h2>
				</div>
			</div>
			<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<p>Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc
						fermentum dapibus. Morbi lorem ante, malesuada in mollis nec,
						auctor nec massa. Aenean tempus dui eget felis blandit at
						fringilla urna ultrices. Suspendisse feugiat, ante et viverra
						lacinia, lectus sem lobortis dui, ultricies consectetur leo mauris
						at tortor.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="content-panel">
					<!-- Content panel in every span for padding -->
					<div class="flexslider">
						<ul class="slides">
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
							<li><img src="<?php echo $this->baseUrl() ?>/default/uploads/tatuadores/1/tatuador.jpg" alt="" /></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	
		

