<footer>
	<section class="container">

		<div class="row">
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">

				<p>contato@electricink.com.br
				<br />
				(34) 3312-8788</p>

			</div>
			<div class="clearfix visible-xs"></div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<ul class="social">
					
					<li>
						<a href="https://www.facebook.com/ElectricinkBrasil" target="_blank">
							<div class="social-facebook"></div>
						</a>
					</li>

				</ul>
			</div>
			<div class="clearfix visible-xs"></div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">

				<p>&copy; <?php echo date('Y');?> Electric Ink. All rights reserved</p>

			</div>
		</div>
	</section>
</footer>