 <div id="footer">
 	<div class="container">
		
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<p>contato@electricink.com.br
				<br />
				(34) 3312-8788
			</p>
		</div>

		<div class="clearfix visible-xs"></div>
		
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
			<ul class="social">
					
				<li>
					<a href="https://www.facebook.com/ElectricinkBrasil" target="_blank">
						<div class="social-facebook"></div>
					</a>
				</li>
				<li>
					<a href="http://www.youtube.com/user/electricinktv" target="_blank">
						<div class="social-youtube"></div>
					</a>
				</li>
		</div>
		
		<div class="clearfix visible-xs"></div>
		
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">

			<p>&copy; <?php echo date('Y');?> Electric Ink. All rights reserved</p>

		</div>	

 	</div>
 </div>