 <div id="footer">
 	<div class="container">
		
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
			<p>
				
				Electric Ink Indústria Comércio Importação e Exportação Ltda.<br />
				Rua Passa Quatro, 398 - Bairro: Bom Retiro<br />
				CEP: 38022-220 / Uberaba - MG
				</p>
		</div>

		<div class="clearfix visible-xs"></div>
		
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<ul class="social">
					
				<li>
					<a href="https://www.facebook.com/ElectricinkBrasil" target="_blank">
						<div class="social-facebook"></div>
					</a>
				</li>
				<li>
					<a href="http://www.youtube.com/user/electricinktv" target="_blank">
						<div class="social-youtube"></div>
					</a>
				</li>
		</div>
		
		<div class="clearfix visible-xs"></div>
		
		<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">

			<p>
				contato@electricink.com.br <br />
				Telefone: +55 (34) 3312-8788<br />
				&copy; <?php echo date('Y');?> Electric Ink. All rights reserved</p>

		</div>	

 	</div>
 </div>