<div class="row-fluid">
    <div class="login-box">
        <div align="center" style="margin: 10px 0">
           <a href="<?php echo $this->baseUrl() ?>/index" target="_blank">
              <img src="<?= $this->baseUrl() ?>/admin/images/logotipo_login.png" alt="Momesso Web Studio" title="Momesso Web Studio">
          </a>
      </div>
      <form class="form-horizontal" action="<?= $this->baseUrl() ?>/admin/login/index" method="post">
        <fieldset>
            
            <div class="input-prepend" title="Username">
                <span class="add-on"><i class="icon-user"></i></span>
                <input class="input-large span10" name="usuario" id="usuario" type="text" placeholder="usuário"/>
            </div>
            <div class="clearfix"></div>

            <div class="input-prepend" title="Password">
                <span class="add-on"><i class="icon-lock"></i></span>
                <input class="input-large span10" name="senha" id="senha" type="password" placeholder="senha"/>
            </div>
            <div class="clearfix"></div>

            <div class="btn-group button-login">
                <button type="submit" class="btn btn-primary"><i class="icon-off icon-white"></i> Login</button>
            </div>
            <div class="clearfix"></div>
        </form>
        
    </div><!--/span-->
</div><!--/row-->
