<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Recuperação de senha</title>
	</head>
	
	<body>	
		<table width="100%" border="0" cellspacing="3" cellpadding="5">	
			<tr>
				<td colspan="2" align="center" valign="middle" bgcolor="#115f0b"><font color="#FFFFFF" face="Arial, Helvetica, sans-serif" size="+1"><strong>Pedido de recuperação de senha</strong></font></td>
			</tr>
			<tr>
				<td width="13%" align="right" valign="middle" bgcolor="#e5e5e5"><strong><font color="#666666" size="2" face="Verdana,Arial, Helvetica, sans-serif">IP da solicitação:</font></strong></td>
				<td valign="top"><font color="#000000" size="2" face="Verdana,Arial, Helvetica, sans-serif"><?php echo Zend_Controller_Front::getInstance()->getRequest()->getServer('REMOTE_ADDR')?></font></td>
			</tr>
			<tr>
				<td width="13%" align="right" valign="middle" bgcolor="#e5e5e5"><strong><font color="#666666" size="2" face="Verdana,Arial, Helvetica, sans-serif">Nome:</font></strong></td>
				<td valign="top"><font color="#000000" size="2" face="Verdana,Arial, Helvetica, sans-serif"><?php echo $this->dados["nome"]?></font></td>
			</tr>
			<tr>
				<td width="13%" align="right" valign="middle" bgcolor="#e5e5e5"><strong><font color="#666666" size="2" face="Verdana,Arial, Helvetica, sans-serif">E-mail:</font></strong></td>
				<td valign="top"><font color="#000000" size="2" face="Verdana,Arial, Helvetica, sans-serif"><?php echo $this->dados["email"]?></font></td>
			</tr>
			<tr>
				<td align="right" valign="middle" bgcolor="#e5e5e5"><strong><font color="#666666" size="2" face="Verdana,Arial, Helvetica, sans-serif">Usuário:</font></strong></td>
				<td valign="top"><font color="#000000" size="2" face="Verdana,Arial, Helvetica, sans-serif"><?php echo $this->dados["usuario"]?></font></td>
			</tr>
			<tr>
				<td align="right" valign="middle" bgcolor="#e5e5e5"><strong><font color="#666666" size="2" face="Verdana,Arial, Helvetica, sans-serif">Nova senha:</font></strong></td>
				<td valign="top"><font color="#000000" size="2" face="Verdana,Arial, Helvetica, sans-serif"><?php echo $this->dados["senha"]?></font></td>
			</tr>
		</table>	
	</body>

</html>