<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>

<section class="container">

	<ol class="breadcrumb">
      <li>Usuário</li>
      <li class="active">Meu Cadastro</li>
    </ol>

    <?php echo $this->Form; ?>

</section>