<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>

<section class="container">

    <ol class="breadcrumb">
      <li>Usuário</li>
      <li class="active">Meus Pedidos</li>
    </ol>


    <div class="table-responsive">
        
        <h3>Pedidos(s)</h3>
        <table class="table table-striped table-hover">
            <tr>
              <th>Número Pedido</th>
              <th>Data</th>
              <th>Forma de Pagamento</th>
              <th>Valor</th>
              <th>Status</th>
              <th></th>
            </tr>
        
            <? foreach ($this->Data as $v) { ?>
            <tr>
                <td><?php echo $v->pedido_numero ;?></td>
                <td><?php echo $this->Data($v->created_at) ;?></td>
                <td><?php echo $v->pagamento ;?></td>
                <td><?php echo $this->Valor($v->valor); ?></td>
                <td>
                <?php  
                
                  switch ($v->status) {
                    
                    case 0:
                    echo 'Pedido não finalizado';
                    break;
                    
                    case 1:
                    echo 'Pedido realizado';
                    break;

                    case 2:
                    echo 'Autorização de pagamento';
                    break;

                    case 3:
                     echo 'Preparação para o envio';
                    break; 

                    case 4:
                     echo 'Transporte do(s) Produto(s)';
                    break;

                    case 5:
                     echo 'Entrega do(s) Produto(s)';
                    break;

                    case 7:
                     echo 'Cancelado';
                    break;  

                  }
                ?> 
                </td>
                <td>
                    <a href="<?php echo $this->baseUrl() ?>/usuario/view/id/<?php echo $v->cod_pedido ;?>" class="btn btn-sm btn-primary">
                        <i class="fa fa-list"></i> Detalhes
                    </a>
                </td>
            </tr>

            <?php } ?>
        
        </table>
    </div>


</section>