<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>

<section class="container">

    <div class="table-responsive">
        
      <ol class="breadcrumb">
        <li>Usuário</li>
        <li><a href="<?php echo $this->baseUrl() ?>/usuario/pedido">Meus Pedidos</a></li>
        <li class="active">Pedido: <?php echo $this->Pedido->pedido_numero ;?></li>
      </ol>

        <h3>Dados do Pedido</h3>
        <table class="table table-striped table-hover">
            <tr align="center">
              <th>Número Pedido</th>
              <th>Data</th>
              <th>Forma de Pagamento</th>
              <th>Valor do Pedido</th>
              <th>Status</th>
            </tr>

            <tr>
              <td><?php echo $this->Pedido->pedido_numero ;?></td>
              <td><?php echo $this->Data($this->Pedido->created_at) ;?></td>
              <td><?php echo $this->Pedido->pagamento ;?></td>
              <td><?php echo $this->Valor($this->Pedido->valor) ;?></td>
              <td>
              <?php  
                
                switch ($this->Pedido->status) {
                  
                  case 1:
                  echo 'Pedido realizado';
                  break;

                  case 2:
                  echo 'Autorização de pagamento';
                  break;

                  case 3:
                   echo 'Preparação para o envio';
                  break; 

                  case 4:
                   echo 'Transporte do(s) Produto(s)';
                  break;

                  case 5:
                   echo 'Entrega do(s) Produto(s)';
                  break; 

                  case 7:
                    echo 'Cancelado';
                  break;  

                }
              ?>  
              </td>
            </tr>
        
        </table>

        <h3>Itens Comprados</h3>
        <table class="table table-striped table-hover">
            <tr>
              <th>Produto</th>
              <th>Quantidade</th>
              <th>Valor Unitário</th>
              <th>Total</th>
            </tr>

            <? foreach ($this->Produtos as $v) { ?>
            <tr>
                <td><?php echo $v->produto ;?></td>
                <td><?php echo $v->quantidade ;?></td>
                <td><?php echo $this->Valor($v->valor); ?></td>
                <td><?php echo $this->Valor($v->valor*$v->quantidade); ?></td>
                <td></td>
            </tr>

            <?php } ?>
        
        </table>
    </div>


</section>