<div id="varejo" class="tab-pane active">
    <?php echo $this->paginationControl($this->Data, 'Sliding', 'render/pagination.phtml') ?> 
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cidade / Estado</th>
                    <th>Tel. Fixo</th>
                    <th>Ativo</th>
                    <th>Ações</th>
                </tr>
            </thead>   
            <tbody>
                <?php foreach ($this->Data as $rs) { ?>
                <tr>
                    <td><?php echo $rs->fantasia; ?></td>
                    <td><?php echo $rs->cidade.' / '.$rs->estado; ?></td>
                    <td><?php echo $rs->telefone_fixo; ?></td>
                    
                    <td class="center">
                        <?php 
                        if($rs->situacao == 1) echo '<span class="label label-success arrowed">Sim</label'; else echo '<span class="label">Não</label';
                        ?>
                    </td>
                    <td class="center">
                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/cliente/edit/id/<?php echo $rs->cod_cliente; ?>">
                            <i class="fa fa-pencil-square-o fa-lg"></i>  
                        </a>
                        <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Excluir" href="<?= $this->BaseUrl() ?>/admin/cliente/delete/id/<?php echo $rs->cod_cliente; ?>" >
                            <i class="fa fa-trash-o fa-lg"></i> 
                        </a>
                    </td>
                    
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->Data, 'Sliding', 'render/pagination.phtml') ?>          
    </div>