<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>
<div class="panel">

	<div class="col-xs-12 col-sm-12">

		<div class="login-box">
		

			<form class="form-horizontal" name="form-password" id="form-password" style="margin-top:20px;" action="<?= $this->baseUrl() ?>/login/forgot" method="post">

				<div class="input-prepend" title="Username">
					<span class="add-on"><i class="fa fa-user"></i></span>
					<input class="form-control" name="email" id="email" type="text" placeholder="E-mail"/>
				</div>

				<div class="clearfix"></div>

				<div class="btn-group button-login">
					<button type="submit" id="bt-password" class="btn btn-primary"><i class="fa fa-share"></i> Enviar Senha</button>
				</div>
			</form>

		</div>

	</div>


</div>