<script type="text/javascript">
function slider_top() {
    $(".slider-bg").backstretch([
         baseUrl+"/default/uploads/banners/background/big-1.jpg", 
         baseUrl+"/default/uploads/banners/background/big-2.jpg", 
         baseUrl+"/default/uploads/banners/background/big-3.jpg", 
         baseUrl+"/default/uploads/banners/background/big-4.jpg"
    ], {
        duration: 10000,
        fade: 750
    });
}
</script>
 <div class="login-box">

  <form class="form-horizontal" action="<?= $this->baseUrl() ?>/login/index" method="post">
    <fieldset>

      <div class="input-prepend" title="Username">
        <span class="add-on"><i class="fa fa-user"></i></span>
        <input class="form-control" name="usuario" id="usuario" type="text" placeholder="e-mail"/>
      </div>
      
      <div class="clearfix"></div>

      <div class="input-prepend" title="Password">
        <span class="add-on"><i class="fa fa-lock"></i></span>
        <input class="form-control" name="senha" id="senha" type="password" maxlength="8" placeholder="senha"/>
      </div>
      <div class="clearfix"></div>

      <a href="<?php echo $this->baseUrl() ?>/login/forgot" class="btn btn-primary"><i class="fa fa-key"></i> Esqueci Minha Senha</a>

        <br />

      <div class="btn-group button-login">
        <button type="submit" class="btn btn-primary"><i class="fa fa-power-off"></i> Login</button>
      </div>
    </form>

  </div>
  <div class="clearfix"></div>       