<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/cliente/new/type/f">
    <i class="fa fa-plus-circle fa-lg"></i> Pessoa Física
</a>

<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/cliente/new/type/j">
    <i class="fa fa-plus-circle fa-lg"></i> Pessoa Jurídica
</a>

<br /><br />


<form class="form-search">
    
    <label for="search">Busca por Nome Cliente</label><br>
    <input type="text" placeholder="Busca por nome" class="nav-search-input" id="search" />
    <a href="#" class="js-busca" rel="cliente/busca/q/"><i class="fa fa-search"></i></a>

</form>


<br /> 

<div class="tabbable">
    
    <ul id="myTab" class="nav nav-tabs">

        <li class="<?php if($this->Grupo == 1 or $this->Grupo == 0) echo 'active'; ?>">
            <a href="cliente/index/grupo/1" class="js-tab" data-target="#varejo" data-toggle="tab">
                Varejo
            </a>
        </li>

        <li class="<?php if($this->Grupo == 2) echo 'active'; ?>">
            <a href="cliente/index/grupo/2" class="js-tab" data-target="#atacado" data-toggle="tab">
                Atacado
            </a>
        </li>

        <li class="<?php if($this->Grupo == 3) echo 'active'; ?>">
            <a href="cliente/index/grupo/3" class="js-tab" data-target="#distribuidor" data-toggle="tab">
                Distribuidor
            </a>
        </li>

    </ul>   

</div>

<br>

<h3>Resultado(s) da busca por: <?php echo $this->Query; ?></h3>    

    <div class="table-responsive">
       <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cidade / Estado</th>
                    <th>Tel. Fixo</th>
                    <th>Ativo</th>
                    <th>Ações</th>
                </tr>
            </thead>   
            <tbody>
                <?php foreach ($this->Data as $rs) { ?>
                <tr>
                    <td><?php echo $rs->fantasia; ?></td>
                    <td><?php echo $rs->cidade.' / '.$rs->estado; ?></td>
                    <td><?php echo $rs->telefone_fixo; ?></td>
                    
                    <td class="center">
                        <?php 
                        if($rs->situacao == 1) echo '<span class="label label-success arrowed">Sim</label'; else echo '<span class="label">Não</label';
                        ?>
                    </td>
                    <td class="center">
                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/cliente/edit/id/<?php echo $rs->cod_cliente; ?>">
                            <i class="fa fa-pencil-square-o fa-lg"></i>  
                        </a>
                        <a class="btn btn-xs btn-danger btn-tooltip" data-toggle="tooltip" data-original-title="Excluir" href="<?= $this->BaseUrl() ?>/admin/cliente/delete/id/<?php echo $rs->cod_cliente; ?>" >
                            <i class="fa fa-trash-o fa-lg"></i> 
                        </a>
                    </td>
                    
                </tr>
                <?php } ?>
            </tbody>
        </table>        
    </div>
