<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/cliente/new/type/f">
    <i class="fa fa-plus-circle fa-lg"></i> Pessoa Física
</a>

<a class="btn btn-sm btn-success" href="<?= $this->BaseUrl() ?>/admin/cliente/new/type/j">
    <i class="fa fa-plus-circle fa-lg"></i> Pessoa Jurídica
</a>

<br /><br />


<form class="form-search">
    
    <label for="search">Busca por Nome Cliente</label><br>
    <input type="text" placeholder="Busca por nome" class="nav-search-input" id="search" />
    <a href="#" class="js-busca" rel="cliente/busca/q/"><i class="fa fa-search"></i></a>

</form>


<br /> 

<div class="tabbable">
    
    <ul id="myTab" class="nav nav-tabs">

        <li class="<?php if($this->Grupo == 1 or $this->Grupo == 0) echo 'active'; ?>">
            <a href="cliente/index/grupo/1" class="js-tab" data-target="#varejo" data-toggle="tab">
                Varejo
            </a>
        </li>

        <li class="<?php if($this->Grupo == 2) echo 'active'; ?>">
            <a href="cliente/index/grupo/2" class="js-tab" data-target="#atacado" data-toggle="tab">
                Atacado
            </a>
        </li>

        <li class="<?php if($this->Grupo == 3) echo 'active'; ?>">
            <a href="cliente/index/grupo/3" class="js-tab" data-target="#distribuidor" data-toggle="tab">
                Distribuidor
            </a>
        </li>

    </ul>   

</div>

<div class="tab-content">
    
    <?php 
    switch ($this->Grupo) {
        case 1:
            echo $this->render('cliente/template/varejo.phtml');
            break;

        case 2:
            echo $this->render('cliente/template/atacado.phtml');
            break;

        case 3:
            echo $this->render('cliente/template/distribuidor.phtml');
            break;                
        
        default:
            echo $this->render('cliente/template/varejo.phtml');
            break;
    }
    ?>

</div>