<div class="top-parallax">
            <div class="display">
                <div class="slider-bg"></div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="title">
                        <h1>Tatuadores</h1>
                    </div>
                </div>
            </div>
            <div class="top"></div>
        </div>
        <div class="doc">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <div class="content-panel-title">
                            <img src="img/tatuadores/marcelo-marzari_home.png" hspace="15" vspace="15" align="left">
                            <h2>Marcelo Marzari</h2>
                        </div>
                        <div class="content-panel" >
                            <h4 style="line-height:24px;">Marcelo Marzari é tatuador profissional desde 2000, executa um trabalho diretamente direcionado aos estilos NEW SCHOOL e FULL COLORS. Vive intensamente submerso no universo da tatuagem e se importa muito com a exclusividade, originalidade e impacto que seus trabalhos terão no corpo das pessoas. Além de trabalhar em diversos países da Europa e América Latina, participar de importantes convenções mundo afora, trocar experiências e técnicas com reconhecidos artistas, também é proprietário da COLOR UP Tattoo Studio em Curitiba-PR/Brasil, estúdio conceituado pela qualidade de seus profissionais. Por ter foco em designs com bold lines e linhas acentuadas, cores fortes e vibrantes, é muito exigente em relação aos materiais que usa, por isso optou pelas tintas ELECTRIC INK e as máquinas PAULO FERNANDO, aponta como pontos fortes a precisão das máquinas, fácil aplicação e duradoura permanência dos pigmentos.</h4>
                    
        
        <h1><?php echo $this->translate("Titulo da Pagina"); ?></h1>

        <ul>
            <li><a href="<?php echo $this->baseUrl().'/language/pt';?>">pt</a></li>
            <li><a href="<?php echo $this->baseUrl().'/language/en'; ?>">en</a></li>
            <li><a href="<?php echo $this->baseUrl().'/language/es'; ?>">es</a></li>
        </ul>

        <p><?php echo $this->translate("Texto Internacionalizado de Exemplo"); ?></p>
        <p><?php echo $this->translate("A data atual é: %1\$s", new Zend_Date()); ?>
        <p><?php echo $this->translate("O valor monetário do locale é:"); ?> <?php echo new Zend_Currency(); ?></p>
        <p><?php echo $this->translate("O locale de tradução é:"); ?> <?php echo $this->translate()->getLocale(); ?></p>
 
                      </div>
                    </div>
                    <div class="span8">
                        <div class="content-panel" >
                            <div class="photoset-grid-lightbox" data-layout="234" style="visibility: hidden;">
                                <img src="img/tatuadores/marcelo-marzari/05_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/05.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/02_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/02.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/07_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/07.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/03_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/03.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/04_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/04.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/06_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/06.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/08_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/08.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/09_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/09.jpg" alt="" />
                                <img src="img/tatuadores/marcelo-marzari/10_mini.jpg" data-highres="img/tatuadores/marcelo-marzari/10.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
            