<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
 
<?php if (($this->pageCount)>1): ?>
<div class="paginacao ui-state-default">
	<span class="ui-widget-content">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
	  <a href="<?php echo $this->url(array('pagina' => $this->previous)); ?>">
	    &lt; Anterior
	  </a> |
	<?php else: ?>
	  <span class="ui-state-disabled">&lt; Anterior</span> |
	<?php endif; ?>
	 
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
	  <?php if ($page != $this->current): ?>
	    <a href="<?php echo $this->url(array('pagina' => $page)); ?>">
	        <?php echo $page; ?>
	    </a> |
	  <?php else: ?>
	    <span class="ui-state-disabled"><?php echo $page; ?></span> |
	  <?php endif; ?>
	<?php endforeach; ?>
	 
	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	  <a href="<?php echo $this->url(array('pagina' => $this->next)); ?>">
	    Proxima &gt;
	  </a>
	<?php else: ?>
	  <span class="ui-state-disabled">Proxima &gt;</span>
	<?php endif; ?>
	</span>
</div>
<?php endif; ?>