<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->
 
<?php if (($this->pageCount)>1): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 de <?php echo $this->totalItemCount; ?>
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('pagina' => $this->first)); ?>">
    Primeira
  </a> |
<?php else: ?>
  <span class="disabled">Primeira</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('pagina' => $this->previous)); ?>">
    &lt; Anterior
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Anterior</span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('pagina' => $this->next)); ?>">
    Proxima &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Proxima &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('pagina' => $this->last)); ?>">
    Última
  </a>
<?php else: ?>
  <span class="disabled">Última</span>
<?php endif; ?>
 
</div>
<?php endif; ?>
