<?php ?>

<a class="btn btn-sm btn-danger" href="<?= $this->BaseUrl() ?>/admin/pedido/retorno">
    <i class="fa fa-trash-o"></i>  Cancelar Pedidos - Não Pagos / Em Aberto
</a>

<br /><br />


<form class="form-search">
    
    <label for="search">Busca por Número Pedido</label><br>
    <input type="text" placeholder="Busca por número" class="nav-search-input" id="search" />
    <a href="#" class="js-busca" rel="pedido/busca/q/"><i class="fa fa-search"></i></a>

</form>

<br />

<div class="tabbable">
    
    <ul id="myTab" class="nav nav-tabs">

        <li class="<?php if($this->Status == 0) echo 'active'; ?>">
            <a href="pedido/index/status/0" class="js-tab" data-target="#aberto" data-toggle="tab">
                Em Aberto
                <span class="badge badge-danger"><?php echo count($this->Aberto);?></span> 
            </a>
        </li>

        <li class="<?php if($this->Status == 1) echo 'active'; ?>">
            <a href="pedido/index/status/1" class="js-tab" data-target="#realizado" data-toggle="tab">
                Pedido Realizado
                <span class="badge badge-danger"><?php echo count($this->Realizado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 2) echo 'active'; ?>">
            <a href="pedido/index/status/2" class="js-tab" data-target="#confirmado" data-toggle="tab">
                Pagamento Confirmado
                <span class="badge badge-danger"><?php echo count($this->Confirmado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 3) echo 'active'; ?>">
            <a href="pedido/index/status/3" class="js-tab" data-target="#entregue" data-toggle="tab">
                Pedido Entregue
                <span class="badge badge-danger"><?php echo count($this->Entregue);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 4) echo 'active'; ?>">
            <a href="pedido/index/status/4" class="js-tab" data-target="#enviado" data-toggle="tab">
                Pedido Enviado
                <span class="badge badge-danger"><?php echo count($this->Enviado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 5) echo 'active'; ?>">
            <a href="pedido/index/status/5" class="js-tab" data-target="#coleta" data-toggle="tab">
                Aguardando Coleta
                <span class="badge badge-danger"><?php echo count($this->Coleta);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 7) echo 'active'; ?>">
            <a href="pedido/index/status/7" class="js-tab" data-target="#cancelado" data-toggle="tab">
                Cancelado
                <span class="badge badge-danger"><?php echo count($this->Cancelado);?></span>
            </a>
        </li>

    </ul>   

</div>

<br>

<h3>Resultado(s) da busca por: <?php echo $this->Query; ?></h3>    

    <div class="table-responsive">
       <table class="table table-striped table-bordered table-hover" id="">
        <thead>
            <tr>
                <th>Ordem</th>
                <th>Data/Hora</th>
                <th>Número</th>
                <th>Cliente</th>
                <th>Ações</th>
            </tr>
        </thead>   
        <tbody>
            <?php 
            $Model_Cliente = new Model_Cliente();   
            foreach ($this->Data as $rs) { 
                $cliente = $Model_Cliente->getClientById($rs->cliente);
                ?>
                <tr>
                    <td><?php echo $rs->cod_pedido; ?></td>
                    <td><?php echo $this->DataHora($v->created_at); ?></td>
                    <td><?php echo $rs->pedido_numero; ?></td>
                    <td><?php echo $cliente->fantasia; ?></td>
                    

                    <td class="center">


                        <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                            <i class="fa fa-print fa-lg"></i>  
                        </a>

                        <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                            <i class="fa fa-file fa-lg"></i>  
                        </a>

                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                            <i class="fa fa-gift fa-lg"></i>  
                        </a>

                        <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                            <i class="fa fa-pencil-square-o fa-lg"></i>  
                        </a>
                    </td>
                    
                </tr>
                <?php } ?>
            </tbody>
        </table>        
    </div>
