<div class="row">
    <div class="col-xs-12"> 
        <div class="table-header"><i class="fa fa-th-large"></i> Pedidos</div>

        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="registros">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php 
                    $Model_Cliente = new Model_Cliente();    
                    foreach ($this->Data as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                        <td class="center">
                            <?php  
                
                                switch ($rs->status) {
                                  
                                    case 0:
                                    echo 'Em aberto';
                                    break;

                                    case 1:
                                    echo 'Pedido realizado';
                                    break;

                                    case 2:
                                    echo 'Autorização de pagamento';
                                    break;

                                    case 3:
                                    echo 'Preparação para o envio';
                                    break; 

                                    case 4:
                                    echo 'Transporte do(s) Produto(s)';
                                    break;

                                    case 5:
                                    echo 'Entrega do(s) Produto(s)';
                                    break; 

                                    case 6:
                                    echo 'Retornado Estoque';
                                    break;  

                                }
                            ?>
                        </td>

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>
                            

                            <?php if ($rs->status == 0 and $rs->retorno_data_hora == '0000-00-00 00:00:00') { ?>
                                <a class="btn btn-warning btn-xs btn-info retorno btn-tooltip" data-toggle="tooltip" data-original-title="Retorno ao Estoque" rel="/admin/pedido/retorno/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-undo fa-lg"></i>  
                                </a>
                            <?php } ?>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->