<?php ?>

<a class="btn btn-sm btn-danger" href="<?= $this->BaseUrl() ?>/admin/pedido/retorno">
    <i class="fa fa-trash-o"></i>  Cancelar Pedidos - Não Pagos / Em Aberto
</a>

<br /><br />


<form class="form-search">
    
    <label for="search">Busca por Número Pedido</label><br>
    <input type="text" placeholder="Busca por número" class="nav-search-input" id="search" />
    <a href="#" class="js-busca" rel="pedido/busca/q/"><i class="fa fa-search"></i></a>

</form>


<br />                  

<div class="tabbable">
    
    <ul id="myTab" class="nav nav-tabs">

        <li class="<?php if($this->Status == 0) echo 'active'; ?>">
            <a href="pedido/index/status/0" class="js-tab" data-target="#aberto" data-toggle="tab">
                Em Aberto
                <span class="badge badge-danger"><?php echo count($this->Aberto);?></span> 
            </a>
        </li>

        <li class="<?php if($this->Status == 1) echo 'active'; ?>">
            <a href="pedido/index/status/1" class="js-tab" data-target="#realizado" data-toggle="tab">
                Pedido Realizado
                <span class="badge badge-danger"><?php echo count($this->Realizado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 2) echo 'active'; ?>">
            <a href="pedido/index/status/2" class="js-tab" data-target="#confirmado" data-toggle="tab">
                Pagamento Confirmado
                <span class="badge badge-danger"><?php echo count($this->Confirmado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 3) echo 'active'; ?>">
            <a href="pedido/index/status/3" class="js-tab" data-target="#entregue" data-toggle="tab">
                Pedido Entregue
                <span class="badge badge-danger"><?php echo count($this->Entregue);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 4) echo 'active'; ?>">
            <a href="pedido/index/status/4" class="js-tab" data-target="#enviado" data-toggle="tab">
                Pedido Enviado
                <span class="badge badge-danger"><?php echo count($this->Enviado);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 5) echo 'active'; ?>">
            <a href="pedido/index/status/5" class="js-tab" data-target="#coleta" data-toggle="tab">
                Aguardando Coleta
                <span class="badge badge-danger"><?php echo count($this->Coleta);?></span>
            </a>
        </li>

        <li class="<?php if($this->Status == 7) echo 'active'; ?>">
            <a href="pedido/index/status/7" class="js-tab" data-target="#cancelado" data-toggle="tab">
                Cancelado
                <span class="badge badge-danger"><?php echo count($this->Cancelado);?></span>
            </a>
        </li>

    </ul>   

</div>


<div class="tab-content">
    
    <?php 
    switch ($this->Status) {
        case 0:
            echo $this->render('pedido/template/aberto.phtml');
            break;

        case 1:
            echo $this->render('pedido/template/realizado.phtml');
            break;

        case 2:
            echo $this->render('pedido/template/confirmado.phtml');
            break;

        case 3:
            echo $this->render('pedido/template/entregue.phtml');
            break;

        case 4:
            echo $this->render('pedido/template/enviado.phtml');
            break;

        case 5:
            echo $this->render('pedido/template/coleta.phtml');
            break;

        case 7:
            echo $this->render('pedido/template/cancelado.phtml');
            break;                        
        
        default:
            echo $this->render('pedido/template/aberto.phtml');
            break;
    }
    ?>

</div>    