<?php $Model_Cliente = new Model_Cliente(); ?>

<a class="btn btn-sm btn-danger" href="<?= $this->BaseUrl() ?>/admin/pedido/retorno">
    <i class="fa fa-trash-o"></i>  Cancelar Pedidos - Não Pagos / Em Aberto
</a>

<br /><br />

<div class="tabbable">
    
    <ul id="myTab" class="nav nav-tabs">

        <li class="active">
            <a href="#aberto" data-toggle="tab">
                Em Aberto
                <span class="badge badge-danger"><?php echo count($this->Aberto);?></span>
            </a>
        </li>

        <li>
            <a href="#realizado" data-toggle="tab">
                Pedido Realizado
                <span class="badge badge-danger"><?php echo count($this->Realizado);?></span>
            </a>
        </li>

        <li>
            <a href="#confirmado" data-toggle="tab">
                Pagamento Confirmado
                <span class="badge badge-danger"><?php echo count($this->Confirmado);?></span>
            </a>
        </li>

        <li>
            <a href="#entregue" data-toggle="tab">
                Pedido Entregue
                <span class="badge badge-danger"><?php echo count($this->Entregue);?></span>
            </a>
        </li>

        <li>
            <a href="#enviado" data-toggle="tab">
                Pedido Enviado
                <span class="badge badge-danger"><?php echo count($this->Enviado);?></span>
            </a>
        </li>

        <li>
            <a href="#coleta" data-toggle="tab">
                Aguardando Coleta
                <span class="badge badge-danger"><?php echo count($this->Coleta);?></span>
            </a>
        </li>

        <li>
            <a href="#cancelado" data-toggle="tab">
                Cancelado
                <span class="badge badge-danger"><?php echo count($this->Cancelado);?></span>
            </a>
        </li>

    </ul>   

</div>


<div class="tab-content">
    
    <div id="aberto" class="tab-pane active">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php 
                        
                    foreach ($this->Aberto as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                      
        </div>
    </div>


    <div id="realizado" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Realizado as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>

    <div id="confirmado" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Confirmado as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>

    <div id="entregue" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Entregue as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>


    <div id="enviado" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Enviado as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>


    <div id="coleta" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Coleta as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Lote / Número Série" href="<?php echo $this->BaseUrl() ?>/admin/pedido/produto/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-gift fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>


    <div id="cancelado" class="tab-pane">
        <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover" id="">
                <thead>
                    <tr>
                        <th>Ordem</th>
                        <th>Data/Hora</th>
                        <th>Número</th>
                        <th>Cliente</th>
                        <th>Valor</th>
                        <th>Envio</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php    
                    foreach ($this->Cancelado as $rs) { 
                        $cliente = $Model_Cliente->getClientById($rs->cliente);
                    ?>
                    <tr>
                        <td><?php echo $rs->cod_pedido; ?></td>
                        <td><?php echo $this->DataHora($v->created_at); ?></td>
                        <td><?php echo $rs->pedido_numero; ?></td>
                        <td><?php echo $cliente->fantasia; ?></td>
                        <td><?php echo $this->Valor($rs->valor+$rs->frete); ?></td>
                        <td><?php echo $rs->frete_tipo; ?></td>
                       

                        <td class="center">
                            
                            
                            <a class="btn btn-xs btn-success btn-tooltip" data-toggle="tooltip" data-original-title="Imprimir Pedido" href="<?php echo $this->BaseUrl() ?>/admin/pedido/printpedido/id/<?php echo $rs->cod_pedido; ?>" target="_blank">
                                <i class="fa fa-print fa-lg"></i>  
                            </a>

                            <a class="btn btn-xs btn-info info btn-tooltip" data-toggle="tooltip" data-original-title="Informações" rel="/admin/pedido/info/id/<?php echo $rs->cod_pedido ?>">
                                <i class="fa fa-file fa-lg"></i>  
                            </a>
                            
                            <a class="btn btn-xs btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/pedido/edit/id/<?php echo $rs->cod_pedido; ?>">
                                <i class="fa fa-pencil-square-o fa-lg"></i>  
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table> 
                     
        </div>
    </div>

</div>    