<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
<?php

$mpdf=new mPDF('utf-8');
$mpdf->SetHeader(date('d/m/Y H:i:s').' | Pedido: '.$this->Pedido->pedido_numero.' | {PAGENO}');
$mpdf->SetFooter(date('d/m/Y H:i:s').' | Pedido: '.$this->Pedido->pedido_numero.' | {PAGENO}');

$mpdf->keep_table_proportions = TRUE;
$mpdf->ignore_table_width = TRUE;

switch ($this->Pedido->status) {
                
  case 1:
    $status = 'Pedido realizado';
    break;

  case 2:
    $status = 'Autorização de pagamento';
    break;

  case 3:
    $status = 'Preparação para o envio';
    break; 

  case 4:
    $status = 'Transporte do(s) Produto(s)';
    break;

  case 5:
    $status = 'Entrega do(s) Produto(s)';
    break; 

  case 7:
    $status = 'Cancelado';
    break;   
}

foreach ($this->Produtos as $v) {
  $itens .= '<tr align="center">
              <td align="center">'.$v->produto.'</td>
              <td align="center">'.$v->quantidade.'</td>
              <td align="center">'.$v->lote_serie.'</td>
              <td align="center">'.$this->Valor($v->valor).'</td>
              <td align="center">'.$this->Valor($v->valor*$v->quantidade).'</td>
          </tr>';

}                 

if ($this->Cliente->grupo==1) $grupo = 'Varejo'; 
if ($this->Cliente->grupo==2) $grupo = 'Atacado'; 
if ($this->Cliente->grupo==3) $grupo = 'Distribuidor';

if(!$this->Erro) {
  
$mpdf->WriteHTML('

<style>

@media print {
  * {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    box-shadow: none !important;
  }
 
  thead {
    display: table-header-group;
  }
  tr,
  img {
    page-break-inside: avoid;
  }
  
  p,
  h2,
  h3 {
    orphans: 3;
    widows: 3;
  }
  h2,
  h3 {
    page-break-after: avoid;
  }
  
  .table td,
  .table th {
    background-color: #fff !important;
  }
  
  .table {
    border-collapse: collapse !important;
  }
  .table-bordered th,
  .table-bordered td {
    border: 1px solid #ddd !important;
  }
}

* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
*:before,
*:after {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
html {
  font-size: 62.5%;

  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}

h1,
h2,
h3,
h4,
h5,
h6,
.h1,
.h2,
.h3,
.h4,
.h5,
.h6 {
  font-family: inherit;
  font-weight: 500;
  line-height: 1.1;
  color: inherit;
}
h1 small,
h2 small,
h3 small,
h4 small,
h5 small,
h6 small,
.h1 small,
.h2 small,
.h3 small,
.h4 small,
.h5 small,
.h6 small,
h1 .small,
h2 .small,
h3 .small,
h4 .small,
h5 .small,
h6 .small,
.h1 .small,
.h2 .small,
.h3 .small,
.h4 .small,
.h5 .small,
.h6 .small {
  font-weight: normal;
  line-height: 1;
  color: #999;
}
h1,
.h1,
h2,
.h2,
h3,
.h3 {
  margin-top: 20px;
  margin-bottom: 10px;
}
h1 small,
.h1 small,
h2 small,
.h2 small,
h3 small,
.h3 small,
h1 .small,
.h1 .small,
h2 .small,
.h2 .small,
h3 .small,
.h3 .small {
  font-size: 65%;
}
h4,
.h4,
h5,
.h5,
h6,
.h6 {
  margin-top: 10px;
  margin-bottom: 10px;
}
h4 small,
.h4 small,
h5 small,
.h5 small,
h6 small,
.h6 small,
h4 .small,
.h4 .small,
h5 .small,
.h5 .small,
h6 .small,
.h6 .small {
  font-size: 75%;
}
h1,
.h1 {
  font-size: 36px;
}
h2,
.h2 {
  font-size: 30px;
}
h3,
.h3 {
  font-size: 24px;
}
h4,
.h4 {
  font-size: 18px;
}
h5,
.h5 {
  font-size: 14px;
}
h6,
.h6 {
  font-size: 12px;
}
p {
  margin: 0 0 10px;
}

table {
  max-width: 100%;
  background-color: transparent;
}
th {
  text-align: left;
}
.table {
  width: 100%;
  margin-bottom: 20px;
}
.table > thead > tr > th,
.table > tbody > tr > th,
.table > tfoot > tr > th,
.table > thead > tr > td,
.table > tbody > tr > td,
.table > tfoot > tr > td {
  padding: 12px;
  line-height: 1.42857143;
  vertical-align: top;
  border-top: 1px solid #ddd;
}
.table > thead > tr > th {
  vertical-align: bottom;
  border-bottom: 2px solid #ddd;
}

.table > tbody + tbody {
  border-top: 2px solid #ddd;
}
.table .table {
  background-color: #fff;
}

.table-bordered {
  border: 1px solid #ddd;
}
.table-bordered > thead > tr > th,
.table-bordered > tbody > tr > th,
.table-bordered > tfoot > tr > th,
.table-bordered > thead > tr > td,
.table-bordered > tbody > tr > td,
.table-bordered > tfoot > tr > td {
  border: 1px solid #ddd;
  padding: 15px;
}
.table-bordered > thead > tr > th,
.table-bordered > thead > tr > td {
  border-bottom-width: 2px;
}
.table-striped > tbody > tr:nth-child(odd) > td,
.table-striped > tbody > tr:nth-child(odd) > th {
  background-color: #f9f9f9;
}


</style>

      
      <h4>Dados do Pedido</h4>
      <b>Número do Pedido:</b> '.$this->Pedido->pedido_numero.'<br />
      <b>Data do Pedido:</b> '.$this->Data($this->Pedido->created_at).'<br />
      <b>Forma de Pagamento:</b> '.$this->Pedido->pagamento.'<br />
      <b>Valor Total dos Produtos:</b> '.$this->Valor($this->Pedido->valor).'<br />
      <b>Valor do Frete:</b> '.$this->Valor($this->Pedido->frete).'<br />
      <b>Forma de Envio:</b> '.$this->Pedido->frete_tipo.'<br />
      <b>Valor Total:</b> '.$this->Valor($this->Pedido->frete+$this->Pedido->valor).'

      <hr />

      <h4>Endereço de Entrega</h4>
      <b>Endereço:</b> '.$this->Cliente->endereco.'-'.$this->Cliente->numero.'<br />
      <b>Complemento:</b> '.$this->Cliente->complemento.'<br />
      <b>Bairro:</b> '.$this->Cliente->bairro.'<br />
      <b>Cidade / Estado:</b> '.$this->Cliente->cidade.' / '.$this->Cliente->estado.'<br />
      <b>CEP:</b> '.$this->Cliente->cep.'

      <hr />

      <h4>Dados do Cliente</h4>
      <b>Nome:</b> '.$this->Cliente->fantasia.'<br />
      <b>Documento:</b> '.$this->Cliente->documento.'<br />
      <b>Grupo:</b> '.$grupo.'<br />
      <b>E-mail: </b>'.$this->Cliente->email.'<br />
      <b>Telefone Fixo:</b> '.$this->Cliente->telefone_fixo.'<br />
      <b>Telefone Celular:</b> '.$this->Cliente->telefone_celular.'
      
      <hr />

      <h4>Produtos Adquiridos</h4>
      <table cellspacing="5" cellpadding="10" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th align="center">Produto</th>
            <th align="center">Qtde</th>
            <th align="center">Lote / Número Série</th>
            <th align="center">Vl. Unitário</th>
            <th align="center">Total</th>
          </tr>
         </thead> 
      <tbody>
          '.$itens.'
      </tbody>
      </table>

');

}else{
   $mpdf->WriteHTML('Os campos de Início / Fim e Situação são obrigatórios o preenchimento.'); 
}

$mpdf->Output();

exit; 


?>