<?php
if ($this->pageCount):
?>

	<div align="center" class="content-panel">
	    <ul class="pagination">
			<?php if (isset($this->previous)): ?>
	            <li><a href="<?php echo $this->url(array('pagina' => $this->previous)); ?>">«</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">«</a></li>
            <?php endif; ?>

    		<?php foreach ($this->pagesInRange as $page): ?>

    			<?php if ($page != $this->current): ?>
	                <li>
	                    <a href="<?php echo $this->url(array('pagina' => $page)); ?>"><?php echo $page; ?></a>
                    </li>                
		        <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>                
		        <?php endif; ?>

    		<?php endforeach; ?>
				<?php if (isset($this->next)): ?>
	                <li><a href="<?php echo $this->url(array('pagina' => $this->next)); ?>">»</a></li>
	            <?php else: ?>
	                <li class="disabled"><a href="#">»</a></li>
	            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>