<a class="btn btn-success" href="<?= $this->BaseUrl() ?>/admin/modulo/new">
    <i class="icon-plus-sign icon-white"></i> Novo Controller
</a>

<br /><br />

<div class="row-fluid sortable">        
    <div class="box span12">  
        <div class="box-header" data-original-title>
            <h2><i class="icon-th-large"></i><span class="break"></span>Controllers</h2>
        </div>                
        <div class="box-content">
             <table class="table table-striped table-hover table-bordered" id="">
                <thead>
                    <tr>
                        <th>Controller</th>
                        <th>Label</th>
                        <th>Visível</th>
                        <th>Ações</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php foreach ($this->Data as $rs) { ?>
                    <tr>
                        <td><?php echo $rs->name; ?></td>
                        <td><?php echo $rs->label; ?></td>
                        <td class="center">
                        	<?php 
                        		if($rs->visible == 1) echo '<span class="label label-success">Sim</label'; else echo '<span class="label label-warning">Não</label>';
                        	?>
                        </td>
                        <td class="center">
                            <a class="btn btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Actions" href="<?php echo $this->BaseUrl() ?>/admin/modulo/action/id/<?php echo $rs->cod_controller; ?>">
                                <i class="icon-cogs icon-white"></i>  
                            </a>
                            <a class="btn btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Editar" href="<?php echo $this->BaseUrl() ?>/admin/modulo/edit/id/<?php echo $rs->cod_controller; ?>">
                                <i class="icon-edit icon-white"></i>  
                            </a>
                            <a class="btn btn-info btn-tooltip" data-toggle="tooltip" data-original-title="Excluir" href="<?= $this->BaseUrl() ?>/admin/modulo/delete/id/<?php echo $rs->cod_controller; ?>" >
                                <i class="icon-trash icon-white"></i> 
                            </a>
                        </td>
                        
                    </tr>
                    <?php } ?>
                </tbody>
            </table>            
        </div>
    </div><!--/span-->
</div><!--/row-->