<table width="100%" border="0" cellspacing="3" cellpadding="5">
  <tr>
    <td colspan="4" align="center" bgcolor="#CCCCCC"><strong>Recuperar Senha</strong></td>
  </tr>
    <tr>
    <td width="16%">Name:</td>
    <td width="38%"><?php echo $this->dados["fantasia"];?></td>
    <td width="18%">E-mail:</td>
      <td width="28%"><?php echo $this->dados["email"];?></td>
  </tr>
    <tr>
    <td colspan="4">Link para resetar sua senha</td>
    </tr>
    <tr>
      <td colspan="4">
        <a href="http://www.electricink.com.br/login/reset/id/<?php echo base64_encode($this->dados["cod_cliente"]);?>">
          Clique para alterar sua senha
        </a></td>
    </tr>
</table>